version: "3.8"

services:
  db-postgres:
    image: postgres:15.3-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: db-pgadmin
    restart: always
    depends_on:
      - db-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5433:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

networks:
  default:
    name: local-network
    external: true